name:                Sandbox
version:             0.1.0.0
github:              "ReedOei/Sandbox"
license:             BSD3
author:              "Reed Oei"
maintainer:          "oei.reed@gmail.com"
copyright:           "2018 Reed Oei"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ReedOei/Sandbox#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- MissingH
- lens
- arithmoi
- split
- optparse-applicative
- terminal-progress-bar
- mtl
- random
- array

library:
  source-dirs: src

executables:
  Sandbox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sandbox

tests:
  Sandbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sandbox
